In [14]:
import numpy as np
arr = np.arange(8)
arr
arr_new = arr.reshape((2, 4), order='F')
print(arr_new)
arr_trans = arr_new.transpose()
print(arr_trans)

[[0 2 4 6]
 [1 3 5 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [26]:
arr2 = np.linspace(1, 12, 12, endpoint=True).reshape(3, 4)
print(arr2)
arr2[::-1, 2]

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


array([11.,  7.,  3.])

In [46]:
data = np.array([4, 9, -4, 3])
print(data)
# datam = np.array(list(map(lambda x: 0 if x < 0 else x, data)))
datam = np.array(list(filter(lambda x: False if x < 0 else True, data)))
print(datam)
# roots = np.sqrt(data)
# print(type(roots[2]))
# print(roots[2] is np.nan)
# np.isnan(roots)

[ 4  9 -4  3]
[4 9 3]


## Задание 8.4 ##
Векторы в геометрии, которые параллельны друг другу, называются сонаправленными.

Также векторы могут быть параллельны и в пространстве. На практике есть несколько способов определить сонаправленность векторов. Один из них: сумма длин сонаправленных векторов должна быть равной длине суммы двух векторов.

С помощью этого критерия найдите пару сонаправленных векторов.

Искать сонаправленные векторы необходимо, выполняя вычисления в Codeboard выше.

In [4]:
import numpy as np
a = np.array([23, 34, 27])
b = np.array([-54, 1,  46])
c = np.array([46, 68, 54])

print(np.linalg.norm(a) + np.linalg.norm(b) == np.linalg.norm(a + b))
print(np.linalg.norm(a) + np.linalg.norm(c) == np.linalg.norm(a + c))
print(np.linalg.norm(b) + np.linalg.norm(c) == np.linalg.norm(b + c))


False
True
False


## Задание 8.5 ##
Найдите пару векторов, расстояние между которыми больше 100

In [5]:
print(np.linalg.norm(a - b))
print(np.linalg.norm(a - c))
print(np.linalg.norm(b - c))

85.901105930017
49.13247398615299
120.6358155772986


## Задание 8.6 ##
Найдите пару перпендикулярных векторов с помощью скалярного произведения (оно должно быть равно нулю).

In [6]:
print(np.sum(a * b))
print(np.sum(a * c))
print(np.sum(b * c))

34
4828
68


## Задание 8.7-10 ##

In [11]:
mystery = np.array([481,  18, 308,  13, 652, 391,  63,  62, 353, 111, 805, 251,  36, 544, 600, 799, 283, 880,
 470, 599, 814, 507, 242, 650, 180, 860, 979, 298, 621, 197, 572, 976, 905, 427, 119, 905,
  64, 430, 742, 563, 382, 211, 228, 760, 567, 366, 103, 409, 211, 952,   5, 493, 151, 267,
 517, 495, 375,  80, 341,  39, 560,  85, 490,  44,  17, 151,  42, 688, 648, 501, 437, 154,
  66,  28, 921, 642, 196, 719, 208, 492, 538, 687, 841, 933, 386, 719, 114, 261, 838, 228,
 120, 508, 316, 476, 233, 902, 698, 471, 604, 172, 993, 790, 557, 129, 446,  64, 317, 997,
 509, 710, 909, 147, 228, 595, 188, 246, 728, 509, 365, 139, 773, 426, 929, 888, 534, 513,
 666,  77, 299, 943, 985, 588, 137,  31, 385, 405, 980, 854, 327, 714, 318, 909, 803, 334,
 130, 949, 532, 640, 820, 975, 889, 240, 878, 294, 899, 488, 639, 961, 819, 649, 939, 163,
 209, 879, 479, 573, 557,  25, 783, 332, 311, 425, 140, 678, 766, 492, 234, 316, 811, 447,
 772, 325, 640, 387, 858, 208, 739, 870, 227, 385,  24, 286,  22, 599, 951, 994, 457,  99,
 238, 172, 549, 932, 412, 545, 713,  19, 785, 931, 684, 333, 630, 752, 191, 949, 200, 361,
 887, 243, 753, 600, 635, 243, 173, 249, 294, 583, 106, 772, 848, 387, 874, 321, 562,  96,
 211, 561, 918, 868, 206, 745, 710, 869, 387, 600, 726, 179, 336, 806, 392, 612])

##### Найдите минимальное значение в массиве
print(mystery.min())
##### Найдите среднее значение массива
print(mystery.mean())
##### Найдите медиану массива.
print(np.median(mystery))
##### Найдите стандартное отклонение значений в массиве
print(np.std(mystery))

5
490.368
491.0
289.01097656663495
